// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkukrzomcitsvyvrnpfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprdWtyem9tY2l0c3Z5dnJucGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDEzMDMsImV4cCI6MjA2NjUxNzMwM30.d8DqvVX1orMc3lpSqSNmT3FFvG-hD-b02xm7tj4-zxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);